spring:
  application:
    name: user-services
  cloud:
    config:
      enabled: false

  datasource:
    url: jdbc:postgresql://localhost:5432/trainingTaskDB
    username: postgres
    password: 123
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

server:
  port: 8081

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    preferIpAddress: true
