spring:
  application:
    name: company-services
  cloud:
    config:
      enabled: false

  datasource:
    #url: jdbc:postgresql://localhost:5432/trainingTaskDB
    url: jdbc:postgresql://host.docker.internal:5432/trainingTaskDB
    username: postgres
    password: 123
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

server:
  port: 8082

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://host.docker.internal:8761/eureka/
  instance:
    preferIpAddress: true
