spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      discovery.locator:
        enabled: true
        lowerCaseServiceId: true
      routes:
        - id: user-service
          uri: http://user-services:8081
          predicates:
          - Path=/api/users/**
        - id: company-service
          uri: http://company-services:8082
          predicates:
            - Path=/api/companies/**

server:
  port: 8085

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://eureka-server:8761/eureka/
  instance:
    preferIpAddress: true
