spring:
  application:
    name: user-services

  datasource:
    url: jdbc:postgresql://database:5432/trainingTaskDB
    username: postgres
    password: "123"
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

server:
  port: 8081

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://eureka-server:8761/eureka/
  instance:
    preferIpAddress: true
